version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn api.main:app --bind 0.0.0.0:38160 -w 4 -k uvicorn.workers.UvicornWorker
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - 38160
    ports:
      - 38160:38160
    volumes:
      - ./data:/app/data

networks:
  default:
    name: traefik_router_network
    external: true
